# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: pipeline-variable-group
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: eggplant-runner@1
  inputs:
    serverURL: 'http://localhost:8000/'
    testConfigID: '2d3beb7f-876c-4387-914e-4d68cee3cfed'
    clientID: 'client:dai:agent:integration'
    clientSecret: '$(clientSecrect)'
